In [2]:
import pandas as pd

movies = pd.read_csv("../data/raw/IMDB-Movie-Dataset(2023-1951).csv")

In [3]:
movies.isnull().sum()

Unnamed: 0     0
movie_id       0
movie_name     0
year          65
genre          0
overview       0
director       0
cast           0
dtype: int64

In [4]:
movies["year"] = movies["year"].fillna("Unknown")

In [6]:
movies = movies[
    ["movie_name",
     "year",
     "genre",
     "overview",
     "director",
     "cast"
     ]
]

In [5]:
movies.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,1,tt15748830,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,2,tt11663228,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,4,tt15732324,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [6]:
movies["movie_name"] = movies["movie_name"].str.lower()
movies["genre"] = movies["genre"].str.lower()
movies["overview"] = movies["overview"].str.lower()
movies["director"] = movies["director"].str.lower()
movies["cast"] = movies["cast"].str.lower()

In [7]:
movies["movie_name"] = movies["movie_name"].str.strip()
movies["director"] = movies["director"].str.strip()
movies["cast"] = movies["cast"].str.strip()
movies["genre"] = movies["genre"].str.strip()

In [8]:
movies["genre"] = movies["genre"].str.replace(", ", " ")
movies["cast"] = movies["cast"].str.replace(", ", " ")

In [9]:
movies.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,jawan,2023,action thriller,a high-octane action thriller which outlines t...,atlee,shah rukh khan nayanthara vijay sethupathi dee...
1,1,tt15748830,jaane jaan,2023,crime drama mystery,a single mother and her daughter who commit a ...,sujoy ghosh,kareena kapoor jaideep ahlawat vijay varma sau...
2,2,tt11663228,jailer,2023,action comedy crime,a retired jailer goes on a manhunt to find his...,nelson dilipkumar,rajinikanth mohanlal shivarajkumar jackie shroff
3,3,tt14993250,rocky aur rani kii prem kahaani,2023,comedy drama family,flamboyant punjabi rocky and intellectual beng...,karan johar,ranveer singh alia bhatt dharmendra shabana azmi
4,4,tt15732324,omg 2,2023,comedy drama,an unhappy civilian asks the court to mandate ...,amit rai,pankaj tripathi akshay kumar yami gautam pawan...

In [10]:
movies["tags"] = (
    movies["genre"] + " " +
    movies["overview"] + " " +
    movies["director"] + " " +
    movies["cast"] + " " 
)

In [11]:
new_df = movies[
    ["movie_name", "year","genre","tags"]
]
print(new_df.head())

                        movie_name  year                genre  \
0                            jawan  2023      action thriller
1                       jaane jaan  2023  crime drama mystery
2                           jailer  2023  action comedy crime
3  rocky aur rani kii prem kahaani  2023  comedy drama family
4                            omg 2  2023         comedy drama

                                                tags
0  action thriller a high-octane action thriller ...
1  crime drama mystery a single mother and her da...
2  action comedy crime a retired jailer goes on a...
3  comedy drama family flamboyant punjabi rocky a...
4  comedy drama an unhappy civilian asks the cour...

In [12]:
new_df["tags"] = new_df["tags"].str.lower()

C:\Users\SAMIRAN\AppData\Local\Temp\ipykernel_24788\2217453925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].str.lower()

In [13]:
new_df.to_csv(
    "../data/processed/imdb_cleaned.csv",
    index=False
)

In [14]:
print(new_df.head(5))

                        movie_name  year                genre  \
0                            jawan  2023      action thriller
1                       jaane jaan  2023  crime drama mystery
2                           jailer  2023  action comedy crime
3  rocky aur rani kii prem kahaani  2023  comedy drama family
4                            omg 2  2023         comedy drama

                                                tags
0  action thriller a high-octane action thriller ...
1  crime drama mystery a single mother and her da...
2  action comedy crime a retired jailer goes on a...
3  comedy drama family flamboyant punjabi rocky a...
4  comedy drama an unhappy civilian asks the cour...

In [15]:
%pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\SAMIRAN\AppData\Roaming\Python\Python314\site-packages (3.9.4)
Requirement already satisfied: click in C:\Users\SAMIRAN\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in C:\Users\SAMIRAN\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\SAMIRAN\AppData\Roaming\Python\Python314\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in C:\Users\SAMIRAN\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\SAMIRAN\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import nltk
import string

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer

In [17]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SAMIRAN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
ps = PorterStemmer()

In [19]:
def preprocess(text):

    # convert to lowercase
    text = text.lower()

    # remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # split into words
    words = text.split()

    # remove stopwords
    words = [word for word in words if word not in stopwords.words("english")]

    # stemming
    words = [ps.stem(word) for word in words]

    return " ".join(words)

In [20]:
new_df["tags"] = new_df["tags"].apply(preprocess)

C:\Users\SAMIRAN\AppData\Local\Temp\ipykernel_24788\1346203754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(preprocess)

In [21]:
new_df["tags"].head()

0    action thriller highoctan action thriller outl...
1    crime drama mysteri singl mother daughter comm...
2    action comedi crime retir jailer goe manhunt f...
3    comedi drama famili flamboy punjabi rocki inte...
4    comedi drama unhappi civilian ask court mandat...
Name: tags, dtype: object

In [22]:
new_df.to_csv(
    "../data/processed/imdb_preprocessed.csv",
    index=False
)

In [23]:
new_df.loc[0, "tags"]

'action thriller highoctan action thriller outlin emot journey man set rectifi wrong societi atle shah rukh khan nayanthara vijay sethupathi deepika padukon'