In [2]:
import pandas as pd

movies = pd.read_csv("../data/raw/IMDB-Movie-Dataset(2023-1951).csv")

In [3]:
movies.isnull().sum()

Unnamed: 0     0
movie_id       0
movie_name     0
year          65
genre          0
overview       0
director       0
cast           0
dtype: int64

In [4]:
movies["year"] = movies["year"].fillna("Unknown")

In [8]:
movies = movies[
    ["movie_name",
     "year",
     "genre",
     "overview",
     "director",
     "cast"
     ]
]

In [9]:
movies.head()

,movie_name,year,genre,overview,director,cast
0,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [10]:
movies["movie_name"] = movies["movie_name"].str.lower()
movies["genre"] = movies["genre"].str.lower()
movies["overview"] = movies["overview"].str.lower()
movies["director"] = movies["director"].str.lower()
movies["cast"] = movies["cast"].str.lower()

In [11]:
movies["movie_name"] = movies["movie_name"].str.strip()
movies["director"] = movies["director"].str.strip()
movies["cast"] = movies["cast"].str.strip()
movies["genre"] = movies["genre"].str.strip()

In [14]:
movies["genre"] = movies["genre"].str.replace(", ", " ")
movies["cast"] = movies["cast"].str.replace(", ", " ")

In [15]:
movies.head()

,movie_name,year,genre,overview,director,cast
0,jawan,2023,action thriller,a high-octane action thriller which outlines t...,atlee,shah rukh khan nayanthara vijay sethupathi dee...
1,jaane jaan,2023,crime drama mystery,a single mother and her daughter who commit a ...,sujoy ghosh,kareena kapoor jaideep ahlawat vijay varma sau...
2,jailer,2023,action comedy crime,a retired jailer goes on a manhunt to find his...,nelson dilipkumar,rajinikanth mohanlal shivarajkumar jackie shroff
3,rocky aur rani kii prem kahaani,2023,comedy drama family,flamboyant punjabi rocky and intellectual beng...,karan johar,ranveer singh alia bhatt dharmendra shabana azmi
4,omg 2,2023,comedy drama,an unhappy civilian asks the court to mandate ...,amit rai,pankaj tripathi akshay kumar yami gautam pawan...

In [16]:
movies["tags"] = (
    movies["genre"] + " " +
    movies["overview"] + " " +
    movies["director"] + " " +
    movies["cast"] + " " 
)

In [18]:
new_df = movies[
    ["movie_name", "year", "tags"]
]
print(new_df.head())

                        movie_name  year  \
0                            jawan  2023
1                       jaane jaan  2023
2                           jailer  2023
3  rocky aur rani kii prem kahaani  2023
4                            omg 2  2023

                                                tags
0  action thriller a high-octane action thriller ...
1  crime drama mystery a single mother and her da...
2  action comedy crime a retired jailer goes on a...
3  comedy drama family flamboyant punjabi rocky a...
4  comedy drama an unhappy civilian asks the cour...

In [19]:
new_df["tags"] = new_df["tags"].str.lower()

In [20]:
new_df.to_csv(
    "../data/processed/imdb_cleaned.csv",
    index=False
)